### ISSUE TITLE
Add Support for Entities

### ISSUE THREAD

**Issue by iso2013** [iso2013/MultiLineAPI#12]
Necessary classes to change/add:
General:
- ✅ Modify Tag and TagLine classes so they are entity/player ambiguous
EventListener:
- ✅ Add EntitySpawnEvent for auto enable
- ✅ Add EntityDeathEvent to handle entity deaths
- ✅ Add EntityDespawnEvent to handle entity removal
- ❌  Add repeating task to teleport armor stands below entities (this may cause problems, because there is no move event... I'll just have to make sure the entities are teleported whenever they're spawned)
- ✅ Add EntityTeleportEvent to handle entity teleports, and updating their tag entities
ProtocolLib:
- ✅ Add Entity Effect handling through ProtocolLib
- ✅ Create pairs on entity spawn through ProtocolLib
- ✅ Mount Repair Packets through ProtocolLib
- ✅ Implement mount packet sending through ProtocolLib
- ✅ Implement hide method through ProtocolLib
- ✅ Listen for which tags should be visible to each player
MultiLineAPI:
- ⬜️ Add API for making a tag only visible to a specific player
- ✅ Modify main MultiLineAPI to support entities as well as players

Completed: 13/14 (92% ✅ )

Testing... ✅

**Comment by DrkMatr1984** [comment]
Nice :) 

This will be a great addition.

**Comment by iso2013** [comment]
![Spoiler Alert](http://i.imgur.com/Ukt5igG.png)
@DrkMatr1984 It's probably going to come soon, I've just got to fix up entity unbindings again :)

**Comment by DrkMatr1984** [comment]
Awesome :) How are you handling the repeating task? Running entity.getLocation() every 10-15 ticks or so? And is that able to be run thread safe as async or will it run on the main thread? Just curious about the internals, I haven't had time to browse your code yet :)

**Comment by DrkMatr1984** [comment]
As soon as this is done I have so many ideas. I've been wanting something like this for a plugin for word bubbles, and so I could create a pseudo TagAPI to trick some of my plugins into thinking I have TagAPI installed. Also wanted to recreate HealthBar, And I could use it in conjunction with custom resourcepacks like wolfiemarios to recreate a MoneyDrop Plugin complete with holograms, since dropped items themselves are an instance of entity. I could have PrimedTnT on detonate say "KA-BOOM" when it explodes. I dunno, the possibilities are endless :)

**Comment by DrkMatr1984** [comment]
Are you able to retrieve the armor stand entity from the lines yet? Like so I wanted to setVelocity() on it and make a DamageIndicator Plugin?

**Comment by iso2013** [comment]
There is no repeating task, I just update the locations whenever the entity becomes seen by a new player.
I haven't pushed the code yet to the branch, (it's not commented or anything yet)

Yeah, it has a lot of potential :D. The only problem with creating a TagAPI bridge (I looked at it), is that TagAPI is an event-based API - MultiLineAPI is not.

Currently the armor stands cannot be retrieved, they are bound to the tag. One thing you could do though is create a copy of it, teleport it to where the tag is (you'd have to fiddle around with the location), then apply the velocity to that and remove the line that's actually on the tag.

**Comment by iso2013** [comment]
Well I figured out why it had so many problems and bugs... I forgot to define the packet types to listen for

**Comment by iso2013** [comment]
~~Sorry, ran into some delays with the fix. It just broke - I have no idea why - all of a sudden the protocol manager just refused to hide entities and such, I'll look tomorrow.~~
Then I've just got to make sure all the issues are still fixed.

EDIT: It was self-disabling.

**Comment by DrkMatr1984** [comment]
Looking Good :) Excited for full entity support!

**Comment by TigerHix** [comment]
Any updates on this? It looks really cool!

**Comment by iso2013** [comment]
@TigerHix I've almost completed a version that supports this and much much more and cool stuffs :D

**Comment by TigerHix** [comment]
Good to hear! You got me excited for the release. 👍
