### ISSUE TITLE
Underground nametags

### ISSUE THREAD

**Issue by WiseHollow** [iso2013/MultiLineAPI#25]
I am building in a flatland world and when I look down, there are tons of nametags all over the place. I'm the only one on because my server is still in development, but this could cause a major problem on a live server. 
There should only be 1 nametag per player, and should be above their head, not underground. 
Running on Spigot 1.11.

**Comment by iso2013** [comment]
Do you ever force stop your server? Doing so doesn't allow MLAPI to delete the line entities and they get saved with the world. This won't be a problem in version 2, coming Soon™

**Comment by WiseHollow** [comment]
Never have forced stop the server. I only use the proper "stop" button that is built into Multicraft. I really hope it's coming soon. It's been quite a long time, my friend. :P hehe

Also, is there a way to cleanup all these entities?

**Comment by iso2013** [comment]
Yeah, it's been awhile. Been dealing with finals at University and now a incredibly fast paced math class haha. Maybe something will be out later today, but no promises ;)

**Comment by WiseHollow** [comment]
I totally understand. I also go to a tough university and its on an accelerated program to speed up how fast you get a degree. I appreciate your hard work. 

Is there a proper way to cleanup these entities that are all over the place? XD

**Comment by iso2013** [comment]
Hmm. Maybe either use MCEdit or something like
`/kill @e[x=-10000,y=-20,z=-10000,dx=20000,dy=15,dz=20000,type=Armor_Stand]`
then repeat that with slimes and silverfish as well

**Comment by iso2013** [comment]
That command should be valid to delete all entities in the void of the specified type but I just typed it off the top of my head so you might want to double check haha

**Comment by WiseHollow** [comment]
Yeah I had tested it and it worked 100%. All clean and pleasant now. Thank you!

**Comment by iso2013** [comment]
No problem.

I managed to get something working :D. Now all I have to do is add the API methods, make sure spectator mode and such are fixed again, and re-add all the documentation comments and I'll be ready for release :)
