### ISSUE TITLE
Remove ProtocolLib

### ISSUE THREAD

**Issue by ghost** [iso2013/MultiLineAPI#34]
Hey,

Can you please remove ProtocolLib, it is easy to fix ur problem.
When you want to teleport, save the entity, remove the entity (rider) from the player, and set it as rider again.

I hope that this will help you,
Tim203

**Comment by iso2013** [comment]
No. This causes way too many issues, the current method is far simpler. I tried
your method - the teleport event never fires if they have an entity on
their head, making it impossible (or incredibly inconvenient compared to
the way it is now) to remove and re-add the entities as you suggest.

Issue closed.
