### ISSUE TITLE
Original nametag reappears

### ISSUE THREAD

**Issue by toxamin** [iso2013/MultiLineAPI#43]
* Steps to reproduce
  enable demo mode, log two accounts into the server
  tp 10 chunks away from one player, tp back
  poof, there's the original nametag (before multilineapi)
* Expected behaviour
  original nametag doesn't appear
* Actual outcome
  original nametag appears and does not disappear until tag is removed and reapplied to player
* Minecraft version (Only 1.12 is officially supported)
  1.12.2

**Comment by iso2013** [comment]
Does this occur on 1.13?

**Comment by iso2013** [comment]
Also, what renderer are you using?

**Comment by iso2013** [comment]
Cannot replicate this on 1.12.2 with either renderer.

Closing in one week unless additional information is provided.
